[project]
name = "slim"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "slim-bindings==0.6.1",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = ["slim/"]
